* overview
** Install bags
** install redirect blocks
** re-route starboard spin halyard
** Backstay
*** install dyneema backstay
     - install backstay
     - rebuild cascade
** new port guy
** electronics
*** compass / heading
    - design compass install
*** MFD
    - design mfd install
*** integrate existing sensors with anything new
*** autopilot
*** recallibrate speed
*** recallibrate wind
*** processor
*** data capture
** replace forestay and foil
** replace bottom with hard paint
** get on a regular maintaince schedule
** cover for engine control
* setup and teardown checklists

** Pre Race
*** running rigging
Note: install sheets in order
1. jib/genoa sheets
   outside shrouds for GP1, inside shrouds for J3
2. spin guys
3. spin sheets
*** rig tune
- adjust the rig based on expected wind at the dock
*** unplug power and leave on dock
- note close the door on the power inlet. This will help keep water
  out of the inlet
  # TODO picture
*** Remove all but one fenders and leave on dock
Leave one fender attached midship. Remove all of the other fenders and
tie them to the dock so they can protect the boat before launching and
on return.
*** Remove any used course tape from the bulkhead and replace
*** store storm board
# TODO where should this go?
*** Turn on electronics
- Instruments
- Mounted VHF
  - STYC (Ballard Cup, etc.) 72
  - CYC is usually 69
- Handheld VHF
- turn on velocitek pro start and insert into console mount
*** Get winch handles 
*** Store Crew Bags by mast
Do not store bags anywhere else.
*** Water Bottles may be stored in sink or refrigerator
*** Food may be stored in refrigerator
*** Engine Check
- oil level
- coolant level
- comparment check
  look for anything broken or worn
- add entry to log including engine hours

* Sail Inventory
** main
- 1 reef
- adjusting battens
# TODO: get sailbag for main
** Upwind
*** Ballard Sails GP1
General Purpose Geneoa 0kn - 15kn
Identified by black band and GP1 on sailbag
Also referred to as geneoa or #1. A racing geneoa would be made of
lighter material to perform better in lighter wind, but with less high
end range. 
# TODO add picture of bag
*** Ballard Sails J3
Racing Jib  15kn - 25kn
# TODO get better idea for wind range
Identified by red band and J3 on sailbag
Also referred to as jib or #3
# TODO add picture of bag
** Downwind
*** Doyle Class S1
0 - 5kn
Identified as white sail with Doyle logo. Also referred to as a 1/2
oz. or 0.5 ounce refering to the weight of the sail material

This sail is in excellent shape and should be used for races where there is light wind.

Because this is a class sail, the size is limited by class rules. A
PHRF S1 could be larger.
# TODO get better idea for upper limit of wind range or when to switch
# to S2.
*** North Clas S1
0 - 5kn
Identified as white sail with North logo. This also has 0.5 oz material

This sail is kind of old and should be used for practices or
inexperienced crew.

*** Ballard Sails PHRF S2
5kn - 12kn
# TODO get a better idea for the upper and lower limits
Identified as an orange sail with a Ballard Sails logo. It should be
stored in the Ballard Sails launch bag.

This sail is almost band new. It should be use while racing for
moderate wind.

Because this is a PHRF sail it has the maximum size allowed without
affecting our rating.

*** North Sails Class S4
12kn - 20kn
# TODO get a better idea for upper limit of wind range
Identified as a blue sail with Nort Sails logo

This is a heavy wind sail. It should be used when the wind gets over
12kn. It is in good shape as it doesn't get used very often. This is a
class sail so it has class size limitations, but since this is used
for heavy air it may not be as much of a performance disadvantage





